version: '3'
services:
  web:
    image: julianmol007/nodejs_app:${BUILD_ID}
    container_name: nodejs_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - network_nodejs_app_${BUILD_ID}
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - network_nodejs_app_${BUILD_ID}

networks:
  network_nodejs_app_${BUILD_ID}: