version: '3'
services:
  web:
    image: julianmol007/${JOB_NAME}_nodejs_app:${BUILD_ID}
    container_name: nodejs_app
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - network_nodejs_app
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - network_nodejs_app

networks:
  network_nodejs_app:
